CREATE TABLE TANCUVNIK (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IMYA VARCHAR2(100) NOT NULL CHECK (IMYA REGEXP '^[А-ЯҐЄІЇа-яґєії\\s]+$'),
    VIK NUMBER NOT NULL CHECK (VIK > 0)
);

-- Таблиця "Анкета"
CREATE TABLE ANKETA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PSYHOLOGICHNIY_STAN VARCHAR(255) NOT NULL,
    DATA_ZAPOVNENNYA DATE NOT NULL,
    TANCUVNIK_ID INT NOT NULL,
    FOREIGN KEY (TANCUVNIK_ID) REFERENCES TANCUVNIK(ID)
);

-- Таблиця "Звіт"
CREATE TABLE ZVIT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    REZULTAT_ANALIZU TEXT NOT NULL,
    REKOMENDACII TEXT,
    DATA_STVORENNYA DATE NOT NULL,
    ANKETA_ID INT NOT NULL,
    OPENAI_API_ID INT NOT NULL,
    FOREIGN KEY (ANKETA_ID) REFERENCES ANKETA(ID),
    FOREIGN KEY (OPENAI_API_ID) REFERENCES OPENAI_API(ID)
);

-- Таблиця "НавчальнийМодуль"
CREATE TABLE NAVCHALNIY_MODUL (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAZVA VARCHAR(150) NOT NULL,
    OPIS TEXT,
    TRIVALIST INT NOT NULL CHECK (TRIVALIST > 0)
);

-- Таблиця "Доступ"
CREATE TABLE DOSTUP (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    STATUS VARCHAR(50) NOT NULL CHECK (STATUS REGEXP '^(активний|неактивний)$'),
    DATA_NADANNYA DATE NOT NULL,
    TANCUVNIK_ID INT NOT NULL,
    FOREIGN KEY (TANCUVNIK_ID) REFERENCES TANCUVNIK(ID)
);

-- Таблиця "Повідомлення"
CREATE TABLE POVIDOMLENNYA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TEKST TEXT NOT NULL,
    DATA_NADSILANNYA DATETIME NOT NULL,
    DOSTUP_ID INT NOT NULL,
    FOREIGN KEY (DOSTUP_ID) REFERENCES DOSTUP(ID)
);

-- Таблиця "OpenAI API"
CREATE TABLE OPENAI_API (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    API VARCHAR(255) NOT NULL
);

-- Таблиця "Психолог"
CREATE TABLE PSYHOLOG (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IMYA VARCHAR(100) NOT NULL,
    NAPRAYAM_ROBOTI VARCHAR(150),
    DOSVID_ROBOTI INT CHECK (DOSVID_ROBOTI >= 0),
    TANCUVNIK_ID INT NOT NULL,
