-- Drop tables if they exist to reset the schema
DROP TABLE IF EXISTS DANCIVNYK CASCADE;
DROP TABLE IF EXISTS ANKETA CASCADE;
DROP TABLE IF EXISTS ZVIT CASCADE;
DROP TABLE IF EXISTS NAVCHALNYYMODYL CASCADE;
DROP TABLE IF EXISTS DOSTUP CASCADE;
DROP TABLE IF EXISTS POVIDOMLENNYA CASCADE;
DROP TABLE IF EXISTS OPENAI_API CASCADE;
DROP TABLE IF EXISTS PSYHOLOG CASCADE;

-- Create DANCIVNYK table
CREATE TABLE DANCIVNYK (
    DANCIVNYK_ID SERIAL PRIMARY KEY,
    IMYA VARCHAR(100) NOT NULL,
    VIK INT NOT NULL CHECK (VIK > 0)
);

-- Create ANKETA table
CREATE TABLE ANKETA (
    ANKETA_ID SERIAL PRIMARY KEY,
    PSYHOLOGICHNYY_STAN VARCHAR(255) NOT NULL,
    DATA_ZAPOVNENNYA DATE NOT NULL,
    DANCIVNYK_ID INT NOT NULL,
    CONSTRAINT FK_ANKETA_DANCIVNYK
    FOREIGN KEY (DANCIVNYK_ID) REFERENCES DANCIVNYK (DANCIVNYK_ID)
    ON DELETE CASCADE
);

-- Create ZVIT table
CREATE TABLE ZVIT (
    ZVIT_ID SERIAL PRIMARY KEY,
    REZULTAT_ANALIZU TEXT NOT NULL,
    REKOMENDATSIYI TEXT,
    DATA_STVORENNYA DATE NOT NULL,
    ANKETA_ID INT NOT NULL,
    OPENAI_API_ID INT NOT NULL,
    CONSTRAINT FK_ZVIT_ANKETA
    FOREIGN KEY (ANKETA_ID) REFERENCES ANKETA (ANKETA_ID)
    ON DELETE CASCADE,
    CONSTRAINT FK_ZVIT_OPENAI_API
    FOREIGN KEY (OPENAI_API_ID) REFERENCES OPENAI_API (OPENAI_API_ID)
    ON DELETE CASCADE
);

-- Create NAVCHALNYYMODYL table
CREATE TABLE NAVCHALNYYMODYL (
    MODUL_ID SERIAL PRIMARY KEY,
    NAZVA VARCHAR(150) NOT NULL,
    OPYS TEXT,
    TRYVALIST INT NOT NULL CHECK (TRYVALIST > 0)
);

-- Create DOSTUP table
CREATE TABLE DOSTUP (
    DOSTUP_ID SERIAL PRIMARY KEY,
    STATUS VARCHAR(50) NOT NULL CHECK (
        STATUS IN ('AKTYVNYI', 'NEAKTYVNYI')
    ),
    DATA_NADANNYA DATE NOT NULL,
    DANCIVNYK_ID INT NOT NULL,
    CONSTRAINT FK_DOSTUP_DANCIVNYK
    FOREIGN KEY (DANCIVNYK_ID) REFERENCES DANCIVNYK (DANCIVNYK_ID)
    ON DELETE CASCADE
);

-- Create POVIDOMLENNYA table
CREATE TABLE POVIDOMLENNYA (
    POVIDOMLENNYA_ID SERIAL PRIMARY KEY,
    TEKST TEXT NOT NULL,
    DATA_NADSLANNYA TIMESTAMP NOT NULL,
    DOSTUP_ID INT NOT NULL,
    CONSTRAINT FK_POVIDOMLENNYA_DOSTUP
    FOREIGN KEY (DOSTUP_ID) REFERENCES DOSTUP (DOSTUP_ID)
    ON DELETE CASCADE
);

-- Create OPENAI_API table
CREATE TABLE OPENAI_API (
    OPENAI_API_ID SERIAL PRIMARY KEY,
    API_KEY VARCHAR(255) NOT NULL
);

-- Create PSYHOLOG table
CREATE TABLE PSYHOLOG (
    PSYHOLOG_ID SERIAL PRIMARY KEY,
    IMYA VARCHAR(100) NOT NULL,
    NAPRYAM_ROBOTY VARCHAR(150),
    DOSVID_ROBOTY INT CHECK (DOSVID_ROBOTY >= 0),
    DANCIVNYK_ID INT NOT NULL,
    CONSTRAINT FK_PSYHOLOG_DANCIVNYK
    FOREIGN KEY (DANCIVNYK_ID) REFERENCES DANCIVNYK (DANCIVNYK_ID)
    ON DELETE CASCADE
);
