name: SQL Linter

on:
  push:
    branches:
      - main

jobs:
  SQLLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Замінили на підтримувану версію Python

      - name: Install SQLFluff
        run: |
          python -m pip install --upgrade pip
          pip install sqlfluff

      - name: Run SQL Linter
        run: |
          sqlfluff lint $GITHUB_WORKSPACE/DataSchema.sql --dialect oracle
