name: SQL Linter

on:
  push:
    branches: [main]

jobs:
  SQLLinter:
    runs-on: ubuntu-latest
    steps:
      # Клонуємо репозиторій
      - name: Checkout Code in Repository
        uses: actions/checkout@v3

      # Встановлюємо SQLFluff
      - name: Install SQL Linter
        run: pip install sqlfluff

      # Виконуємо перевірку SQL-коду
      - name: Run SQL Linter
        run: |
          sqlfluff lint $GITHUB_WORKSPACE/DataSchema.sql --dialect mysql
