name: Print Software Versions
on:
  push:
    branches:
      - main

jobs:
  PrintLanguageVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Node.js version
        run: |
          echo "Checking Node.js version..."
          node --version || echo "Node.js is not installed."

  PrintDBMSVersions:
    runs-on: ubuntu-latest
    needs: [PrintLanguageVersions]  # Дочікуємось завершення PrintLanguageVersions
    steps:
      - name: Print PostgreSQL version
        run: |
          echo "Checking PostgreSQL version..."
          psql --version || echo "PostgreSQL is not installed."
