name: Print Software Versions

on:
  push:
    branches:
      - main

jobs:
  PrintLanguageVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Node.js version
        run: |
          echo "Checking Node.js version..."
          if command -v node; then
            node --version
          else
            echo "Node.js is not installed."
          fi

  PrintDBMSVersions:
    runs-on: ubuntu-latest
    needs: [PrintLanguageVersions]
    steps:
      - name: Print PostgreSQL version
        run: |
          echo "Checking PostgreSQL version..."
          if command -v psql; then
            psql --version
          else
            echo "PostgreSQL is not installed."
          fi
