name: Print Software Versions

on:
  push:
    branches: [main]

jobs:
  # Print software versions at the data processing level
  PrintClientAndServerSoftwareVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Operating System (Client)
        run: uname -a  # Print information about the client operating system

      - name: Print React CLI Version
        run: npx create-react-app --version  # Print React CLI version

      - name: Print Node.js Version (Server)
        run: node --version  # Print the version of Node.js used on the server

  # Print database versions at the data access level
  PrintDatabaseServerVersion:
    runs-on: ubuntu-latest
    needs: [PrintClientAndServerSoftwareVersions]
    steps:
      - name: Install PostgreSQL Client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client  # Install PostgreSQL client

      - name: Print PostgreSQL Version
        run: psql --version  # Print the version of PostgreSQL client
